<h2>Orders</h2>
<table class="table">
	<tr>
		<th>Name</th>
		<th>Thumbnail</th>
		<th>Description</th>
		<th>&nbsp;</th>
	</tr>
		<? foreach($products as $product) : ?>
		<tr>
			<td>
				<?=$product->name?>
			</td>
			<td>
				<?=$product->thumbnail?>
			</td>
			<td>
				<?=$product->description?>
			</td>
			<td>
				<a href="<?=$this->url('application/admin', array('action' => 'edit', ))?>">Edit</a> | 
				<a href="<?=$this->url('application/admin', array('action' => 'delete', ))?>">Delete</a>
			</td>
		</tr>
		<? endforeach; ?>
</table>
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body…</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>