<h2>Orders</h2>
<table class="table">
	<tr>
		<th>Order ID</th>
		<th>User ID</th>
		<th>Product</th>
		<th>Quantity</th>
		<th>Status</th>
		<th>Payment Method</th>
		<th>Date</th>
	</tr>
		<?if (is_object($orders)): ?>
		<? foreach($orders as $order) : ?>
		<tr>
			<td>
			<?=$order->id?>
			</td>
			<td>
				<?=$order->user_id?>
			</td>
			<td>
				<?=$order->product?>
			</td>
			<td>
				<?=$order->quantity?>
			</td>
			<td>
				<?=$order->status?>
			</td>
			<td>
				<?=$order->paymentMethod?>
			</td>
			<td>
				<?=$order->date?>
			</td>
		</tr>
		<? endforeach; ?>
		<? endif; ?>
</table>
